export const CATEGORIES = [
    { "label": "Airlines", "value": "Airlines" },
    { "label": "Alcohol", "value": "Alcohol" },
    { "label": "Apps", "value": "Apps" },
    { "label": "Beauty", "value": "Beauty" },
    { "label": "Beverages", "value": "Beverages" },
    { "label": "Black community", "value": "Black community" },
    { "label": "Books", "value": "Books" },
    { "label": "Business", "value": "Business" },
    { "label": "Celebrities", "value": "Celebrities" },
    { "label": "Climate Change", "value": "Climate Change" },
    { "label": "Computer Game", "value": "Computer Game" },
    { "label": "Conference", "value": "Conference" },
    { "label": "Corporate Social Responsibility", "value": "Corporate Social Responsibility" },
    { "label": "Culture", "value": "Culture" },
    { "label": "Ecommerce", "value": "Ecommerce" },
    { "label": "Education", "value": "Education" },
    { "label": "Electronics", "value": "Electronics" },
    { "label": "Entertainment", "value": "Entertainment" },
    { "label": "Erotic", "value": "Erotic" },
    { "label": "Events", "value": "Events" },
    { "label": "Family", "value": "Family" },
    { "label": "Fashion", "value": "Fashion" },
    { "label": "Finance", "value": "Finance" },
    { "label": "Fitness", "value": "Fitness" },
    { "label": "Food&drink", "value": "Food&drink" },
    { "label": "Fun", "value": "Fun" },
    { "label": "Gambling", "value": "Gambling" },
    { "label": "Gov officials & agencies", "value": "Gov officials & agencies" },
    { "label": "Healthcare", "value": "Healthcare" },
    { "label": "Hobbies and interest", "value": "Hobbies and interest" },
    { "label": "Household", "value": "Household" },
    { "label": "Internet", "value": "Internet" },
    { "label": "LGBTQ+", "value": "LGBTQ+" },
    { "label": "Magazines", "value": "Magazines" },
    { "label": "Media", "value": "Media" },
    { "label": "Motor", "value": "Motor" },
    { "label": "Movies", "value": "Movies" },
    { "label": "Music", "value": "Music" },
    { "label": "News", "value": "News" },
    { "label": "Newspapers", "value": "Newspapers" },
    { "label": "Night Life", "value": "Night Life" },
    { "label": "Non profits", "value": "Non profits" },
    { "label": "Online Show", "value": "Online Show" },
    { "label": "Pets", "value": "Pets" },
    { "label": "Place", "value": "Place" },
    { "label": "Politics", "value": "Politics" },
    { "label": "Professional Association", "value": "Professional Association" },
    { "label": "Radio", "value": "Radio" },
    { "label": "Religion", "value": "Religion" },
    { "label": "Restaurants&cafes", "value": "Restaurants&cafes" },
    { "label": "Science", "value": "Science" },
    { "label": "Services", "value": "Services" },
    { "label": "Shopping", "value": "Shopping" },
    { "label": "Society", "value": "Society" },
    { "label": "Sports", "value": "Sports" },
    { "label": "Technology", "value": "Technology" },
    { "label": "Telecom", "value": "Telecom" },
    { "label": "Top brands", "value": "Top brands" },
    { "label": "Travel", "value": "Travel" },
    { "label": "TV", "value": "TV" },
    { "label": "Blogs", "value": "Blogs" },
    { "label": "Facebook", "value": "Facebook" },
    { "label": "Instagram", "value": "Instagram" },
    { "label": "Journalist", "value": "Journalist" },
    { "label": "LinkedIn", "value": "LinkedIn" },
    { "label": "Medium", "value": "Medium" },
    { "label": "Pinterest", "value": "Pinterest" },
    { "label": "Podcasts", "value": "Podcasts" },
    { "label": "Snapchat", "value": "Snapchat" },
    { "label": "TikTok", "value": "TikTok" },
    { "label": "Twitch", "value": "Twitch" },
    { "label": "YouTube", "value": "YouTube" }
  ];